module.exports = {
  aboutUsSidebar: [
    {
      type: 'category',
      label: 'About Us',
      items: [{ type: 'autogenerated', dirName: 'about-us' }],
    },
  ],
  worksSidebar: [
    {
      type: 'category',
      label: 'Projects',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'works/projects' }],
    },
    {
      type: 'category',
      label: 'Communities',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'works/community' }],
    },
  ],
  careersSidebar: [
    {
      type: 'category',
      label: 'Careers',
      items: [
        { type: 'autogenerated', dirName: 'careers' },
      ],
    },
  ],
};
