workflows:
  version: 2 
  node-android-ios: 
      jobs:
      - test 

      - android: 
        requires: 
        - test 
        filters: 
         branches: 
          ignore: 
           — master 
            

 - build_deploy_android dev: 
   filters:
    branches:
     only: master 

 - build deploy_android_staging:
   filters:
    branches:
     only: staging 
