import icCareers from '../../static/icon/careers.svg';
import icCopy from '../../static/icon/copy.png';
import icCrossPlatformKoreaLogo from '../../static/icon/cross_platform_korea_logo.png';
import icCrossPlatformKoreaLogoCircle from '../../static/icon/cross_platform_korea_logo_circle.png';
import icFavicon from '../../static/icon/dooboolab_favicon.png';
import icGithubLogo from '../../static/icon/github_logo.png';
import icLogo from '../../static/icon/dooboolab_logo.png';
import icLogoDark from '../../static/icon/dooboolab_logo_dark.png';
import icLogoIntroCut from '../../static/icon/dooboolab_logo_intro_cut.svg';
import icLogoIntroLoop from '../../static/icon/dooboolab_logo_intro_loop.svg';
import icOurStory from '../../static/icon/our_story.svg';
import icTwitterLogo from '../../static/icon/twitter_logo.png';
import icWorks from '../../static/icon/works.svg';
import icYoutubeLogo from '../../static/icon/youtube_logo.png';
import imgCrossPlatformKoreaBoarding from '../../static/img/cross_platform_korea_boarding.png';
import imgLocation from '../../static/img/location.png';

export const IcCareers = icCareers;
export const IcCopy = icCopy;
export const IcCrossPlatFormKorea = icCrossPlatformKoreaLogo;
export const IcCrossPlatFormKoreaCircle = icCrossPlatformKoreaLogoCircle;
export const IcFavicon = icFavicon;
export const IcGithub = icGithubLogo;
export const IcLogo = icLogo;
export const IcLogoDark = icLogoDark;
export const IcLogoIntroCut = icLogoIntroCut;
export const IcLogoIntroLoop = icLogoIntroLoop;
export const IcOurStory = icOurStory;
export const IcTwitter = icTwitterLogo;
export const IcWorks = icWorks;
export const IcYoutube = icYoutubeLogo;
export const ImgCrossPlatformKoreaBoarding = imgCrossPlatformKoreaBoarding;
export const ImgLocation = imgLocation;
