import {ImageSourcePropType} from 'react-native';
import coffee from '../assets/icons/coffee.png';
import doobooIAP from '../assets/icons/dooboo-iap.png';
import doobooUi from '../assets/icons/dooboo-ui.png';
import doobooUiDark from '../assets/icons/dooboo-ui-dark.png';
import dooboolab from '../assets/icons/dooboolab.png';
import dooboolabDark from '../assets/icons/dooboolab-dark.png';
import facebook from '../assets/icons/icFacebook.png';
import google from '../assets/icons/icGoogle.png';
import hackatalk from '../assets/icons/hackatalk.png';
import hackatalkDark from '../assets/icons/hackatalk-dark.png';
import icCamera from '../assets/icons/camera.png';
import icGuest from '../assets/icons/guest.png';
import labtop from '../assets/images/labtop.jpg';
import logo from '../assets/icons/logo.png';
import prismaKorea from '../assets/images/prisma-korea.png';
import puzz from '../assets/icons/puzz.png';
import reactNativeSeoul from '../assets/images/react-native-seoul.png';
import symbol from '../assets/images/symbol.jpg';
import wecount from '../assets/icons/wecount.png';

export const IC_DOOBOO_UI = doobooUi as ImageSourcePropType;
export const IC_DOOBOO_UI_DARK = doobooUiDark as ImageSourcePropType;
export const IC_DOOBOOLAB = dooboolab as ImageSourcePropType;
export const IC_DOOBOOLAB_DARK = dooboolabDark as ImageSourcePropType;
export const IC_HACKATALK = hackatalk as ImageSourcePropType;
export const IC_HACKATALK_DARK = hackatalkDark as ImageSourcePropType;
export const IC_FACEBOOK = facebook as ImageSourcePropType;
export const IC_GOOGLE = google as ImageSourcePropType;
export const IC_WECOUNT = wecount as ImageSourcePropType;
export const IC_PUZZ = puzz as ImageSourcePropType;
export const IC_COFFEE = coffee as ImageSourcePropType;
export const IC_DOOBOO_IAP = doobooIAP as ImageSourcePropType;
export const IC_LOGO = logo as ImageSourcePropType;
export const IC_GUEST = icGuest;
export const IC_CAMERA = icCamera;

export const IMG_SYMBOL = symbol as ImageSourcePropType;
export const IMG_RN_SEOUL = reactNativeSeoul as ImageSourcePropType;
export const IMG_LABTOP = labtop as ImageSourcePropType;
export const IMG_PRISMA_KOREA = prismaKorea as ImageSourcePropType;
