name: Check Website
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install packages
        run: yarn install --ignore-engines

      - name: Type check
        run: yarn tsc

      - name: Build
        run: yarn build

      - name: Check swizzle
        run: |
          yarn swizzle

      - name: Check translations
        run: |
          yarn write-translations

      - name: Write heading ids
        run: |
          yarn write-heading-ids
